Prefix: "&c&lEVENT&f&l »"
EventServer: "event" # Your Bungeecord Event Server Name
Duration: 300 # Events Duration In Seconds
Messages:
  NoPermission: "&cYou Dont Have Enough Permissions." # eventcore.admin
  AlreadyStarted: "&cThere Is A Active Event."
  NoDescription: "&dA Normal Event Has Been Started. Use \"/Event Join\" To Participate."
  EventEnd: "&dEvent Has Been Ended. No One Can Join Now."
  NoActiveEvent: "&cNo Events Are Currently Available."
  Bossbar: "&aJoin Now! &d[Desc]" # [Desc] -> Is A Specific Description Of The Event
Titles:
  Title: "&cEvent Started!"
  Subtitle: "&d/Event Join"
  FadeIn: 10 # In Ticks
  Stay: 20 # In Ticks
  FadeOut: 10 # In Ticks
