name: Event-Core
version: '${project.version}'
main: ir.mehran1022.eventcore.Main
api-version: 1.13
softdepend:
  - Vault
  - Essentials
commands:
  event:
    description: An utility command that helps you create and announce in-game events.
    aliases:
      - event-core
      - ec
    usage: "Usage: /ec help"