Update-Check: true # Checks For Available Update
Auto-Update: false # Automatically Downloads Updates
Prefix: "&c&lEVENT&f&l »&r"
EventServer: "event" # Your Bungeecord Event Server Name
Duration: 300 # Events Duration In Seconds
Cost: # Withdraw Money From Players On Joining
  Enabled: true
  Cost: 15.0

## !!!! Visit https://github.com/Mehran1022mm/Event-Core/wiki For Gradient And Special Colors Usage !!!!
Messages:
  NoPermission: "&cYou Dont Have Enough Permissions." # eventcore.admin
  AlreadyStarted: "&cThere Is A Active Event."
  NoDescription: "&dA Normal Event Has Been Started. Use \"/Event Join\" To Participate."
  EventEnd: "&dEvent Has Been Ended. No One Can Join Now."
  NoActiveEvent: "&cNo Events Are Currently Available."
  Bossbar: "&aJoin Now! &d[Desc]" # [Desc] -> Is A Specific Description Of The Event
  Offline: "&c[Player] Is Offline." # [Player] -> Is Specified Player In Args[1]
  Block: "&aBlocked [Player] From Events."
  Unblock: "&aUnblocked [Player] From Events."
  Blocked: "&cYou Can't Join Because You Are Blocked By An Administrator."
## !!!! Visit https://github.com/Mehran1022mm/Event-Core/wiki For Gradient And Special Colors Usage !!!!

Titles:
  Title: "&cEvent Started!"
  Subtitle: "&d/Event Join"
  FadeIn: 10 # In Ticks
  Stay: 20 # In Ticks
  FadeOut: 10 # In Ticks
